name: slam_the_dead
description: Cross-platform Flutter app comparing Dead Reckoning and SLAM localisation.
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.69.0
  sensors_plus: ^6.0.1
  camera: ^0.11.0+2
  vector_math: ^2.1.4
  async: ^2.11.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/sample_logs/

